Repository DassHydro/smash, pull requests merged in 2023-07, with the labels that each got.

#34 FIX: max_duration event segmentation algorithm
  doc/source/math_num_documentation/signal_analysis/hydrograph_segmentation.rst
  doc/source/release/0.5.0-notes.rst
  smash/core/_event_segmentation.py
  smash/core/model.py
Labels: bug, documentation

#36 Fix : When the rainfall data is spatially desagregated, a temporary n…
  doc/source/release/0.5.0-notes.rst
  smash/tools/raster_handler.py
Labels: bug

#39 Fix start time equal end time
  doc/source/release/0.5.0-notes.rst
  smash/core/_build_model.py
Labels: bug

#42 FIX: resolve issue on flow distances computation
  doc/source/release/0.5.0-notes.rst
  smash/mesh/mw_meshing.f90
Labels: bug

#43 Merge maintenance/0.5.x into main - version 0.5.0
  doc/source/api_reference/hdf5_handler.rst
  doc/source/api_reference/hdf5_io.rst
  doc/source/api_reference/index.rst
  doc/source/api_reference/object_handler.rst
  doc/source/api_reference/raster_handler.rst
  doc/source/math_num_documentation/signal_analysis/hydrograph_segmentation.rst
  doc/source/release/0.5.0-notes.rst
  doc/source/release/index.rst
  doc/source/user_guide/in_depth/optimize/bayes_optimize.rst
  setup.py
  smash/__init__.py
  smash/core/_build_model.py
  smash/core/_constant.py
  smash/core/_event_segmentation.py
  smash/core/_read_input_data.py
  smash/core/model.py
  smash/core/signatures.py
  smash/core/simulation/_optimize.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/bayes_optimize.py
  smash/io/hdf5_io.py
  smash/mesh/mw_meshing.f90
  smash/solver/derived_type/mwd_setup.f90
  smash/solver/forward/forward_db.f90
  smash/solver/optimize/mw_optimize.f90
  smash/solver/optimize/mwd_cost.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
  smash/tools/__init__.py
  smash/tools/hdf5_handler.py
  smash/tools/object_handler.py
  smash/tools/raster_handler.py
  venv_install.sh
Labels: new release

#47 Fix missing ci missing api doc
  doc/source/api_reference/hdf5_handler.rst
  doc/source/api_reference/hdf5_io.rst
  doc/source/api_reference/object_handler.rst
  doc/source/release/0.5.1-notes.rst
  doc/source/release/index.rst
  smash/core/_constant.py
  smash/core/simulation/_standardize.py
  smash/tests/core/test_constant.py
Labels: bug

#50 ENC: enhancing and cleaning signal analysis for Python functions and Fortran routines
  doc/source/release/0.5.0-notes.rst
  doc/source/release/1.0.0-notes.rst
  f90wrap_utils/py_mod_names
  makefile.dep
  setup.py
  smash/__init__.py
  smash/_constant.py
  smash/core/signal_analysis/__init__.py
  smash/core/signal_analysis/metrics/__init__.py
  smash/core/signal_analysis/metrics/_standardize.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/core/signal_analysis/scores/_standardize.py
  smash/core/signal_analysis/scores/scores.py
  smash/core/signal_analysis/segmentation/_standardize.py
  smash/core/signal_analysis/segmentation/_tools.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/_computation.py
  smash/core/signal_analysis/signatures/_standardize.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/factory/mesh/_standardize.py
  smash/fcore/forward/forward_db.f90
  smash/fcore/optimize/mwd_cost.f90
  smash/fcore/routine/md_stats.f90
  smash/fcore/signal_analysis/mwd_metrics.f90
  smash/fcore/signal_analysis/mwd_signatures.f90
  smash/tests/baseline.hdf5
  smash/tests/core/signal_analysis/test_metrics.py
  smash/tests/core/signal_analysis/test_segmentation.py
  smash/tests/core/signal_analysis/test_signatures.py
  smash/tests/diff_baseline.csv
  smash/tests/gen_baseline.py
  smash/tests/simulated_discharges.hdf5
  smash/tests/test_define_global_vars.py
Labels: enhancement

#51 ENC: New parameters structure
  smash/_constant.py
  smash/core/model/_build_model.py
  smash/core/model/_standardize.py
  smash/core/model/model.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/run.py
  smash/factory/dataset/Cance/setup_Cance.yaml
  smash/factory/dataset/France/setup_France.yaml
  smash/factory/dataset/Lez/setup_Lez.yaml
  smash/fcore/common/md_constant.f90
  smash/fcore/derived_type/mwd_control.f90
  smash/fcore/derived_type/mwd_mesh.f90
  smash/fcore/derived_type/mwd_opr_parameters.f90
  smash/fcore/derived_type/mwd_opr_states.f90
  smash/fcore/derived_type/mwd_optimize_options.f90
  smash/fcore/derived_type/mwd_output.f90
  smash/fcore/derived_type/mwd_parameters.f90
  smash/fcore/derived_type/mwd_physio_data.f90
  smash/fcore/derived_type/mwd_setup.f90
  smash/fcore/derived_type/mwd_sparse_matrix.f90
  smash/fcore/forward/forward.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/md_forward_structure.f90
  smash/fcore/optimize/mw_optimize.f90
  smash/fcore/routine/md_stats.f90
  smash/fcore/routine/mwd_parameters_manipulation.f90
  smash/fcore/routine/mwd_sparse_matrix_manipulation.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
  smash/tests/factory/test_samples.py
  smash/tests/test_constant.py
  tapenade/makefile
Labels: enhancement

#52 ENC: Forward run and optimize
  f90wrap_utils/finalize_f90wrap.py
  f90wrap_utils/py_mod_names
  makefile.dep
  smash/_constant.py
  smash/_typing.py
  smash/core/model/_standardize.py
  smash/core/model/model.py
  smash/core/signal_analysis/signatures/_standardize.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/_standardize.py
  smash/core/simulation/run/run.py
  smash/fcore/_f90wrap_decorator.py
  smash/fcore/derived_type/mwd_cost_options.f90
  smash/fcore/derived_type/mwd_mesh.f90
  smash/fcore/derived_type/mwd_optimize_options.f90
  smash/fcore/derived_type/mwd_options.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/md_forward_structure.f90
  smash/fcore/optimize/mw_optimize.f90
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_optimize.py
  smash/tests/core/simulation/test_run.py
  smash/tests/diff_baseline.csv
  smash/tests/gen_baseline.py
  tapenade/makefile
Labels: enhancement
