Repository DassHydro/smash, pull requests merged in 2023-12, with the labels that each got.

#106 ENC: Add a fast access to any atmospheric data
  smash/_constant.py
  smash/core/model/_read_input_data.py
  smash/core/model/_standardize.py
  smash/fcore/derived_type/mwd_setup.f90
Labels: enhancement

#107 Maint inrae branding and doc linkcode
  README.md
  doc/source/_static/corporate_logo.svg
  doc/source/_static/corporate_logo_dark.svg
  doc/source/_static/css/smash.css
  doc/source/_static/favicon.ico
  doc/source/_static/logo_smash.svg
  doc/source/_static/logo_smash_dark.svg
  doc/source/_templates/corporate-logo.html
  doc/source/api_reference/fortran/index.rst
  doc/source/api_reference/index.rst
  doc/source/api_reference/returned_objects/index.rst
  doc/source/conf.py
  doc/source/getting_started/index.rst
  f90wrap/finalize_f90wrap.py
  setup.py
  smash/_constant.py
  smash/core/model/_read_input_data.py
  smash/core/model/_standardize.py
  smash/core/model/model.py
  smash/core/signal_analysis/metrics/_standardize.py
  smash/core/signal_analysis/segmentation/_standardize.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/_standardize.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_doc.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/estimate/_standardize.py
  smash/core/simulation/estimate/_tools.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/_standardize.py
  smash/core/simulation/run/run.py
  smash/factory/mesh/_standardize.py
  smash/factory/mesh/mesh.py
  smash/factory/net/_standardize.py
  smash/factory/net/net.py
  smash/factory/samples/_standardize.py
  smash/factory/samples/samples.py
  smash/fcore/derived_type/mwd_serr_sigma_parameters.f90
  smash/fcore/forward/forward_db.f90
  smash/io/handler/_hdf5_handler.py
  smash/util/_doctools.py
  smash/util/_typing.py
Labels: documentation

#109 Doc optimize control info
  doc/source/api_reference/principal_methods/simulation.rst
  smash/core/model/model.py
  smash/core/simulation/_doc.py
  smash/core/simulation/control.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/run.py
Labels: documentation

#111 MAINT: Switch from setup.py to pyproject.toml
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#112 DOC: Update docstrings for signal analysis methods
  smash/core/model/_read_input_data.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
Labels: documentation

#116 MAINT: Update .gitignore
  .gitignore
Labels: maintenance

#118 FIX: fix error message for missing descriptors and checking uniform descriptors
  smash/_constant.py
  smash/core/model/_read_input_data.py
  smash/core/simulation/_standardize.py
Labels: maintenance

#119 FIX: minor fix doc api model_ddt
  smash/io/model_ddt.py
Labels: documentation
