Repository DassHydro/smash, pull requests merged in 2023-10, with the labels that each got.

#87 Enc bayesian optimize
  doc/source/api_reference/principal_methods/model.rst
  doc/source/api_reference/principal_methods/simulation.rst
  doc/source/api_reference/returned_objects/index.rst
  f90wrap_utils/kind_map
  f90wrap_utils/py_mod_names
  makefile.dep
  smash/__init__.py
  smash/_constant.py
  smash/core/model/_build_model.py
  smash/core/model/_read_input_data.py
  smash/core/model/_standardize.py
  smash/core/model/model.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/_tools.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/control.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/_standardize.py
  smash/factory/mesh/mesh.py
  smash/factory/net/_loss.py
  smash/fcore/derived_type/mwd_control.f90
  smash/fcore/derived_type/mwd_cost_options.f90
  smash/fcore/derived_type/mwd_optimize_options.f90
  smash/fcore/derived_type/mwd_parameters.f90
  smash/fcore/derived_type/mwd_returns.f90
  smash/fcore/derived_type/mwd_serr_mu_parameters.f90
  smash/fcore/derived_type/mwd_serr_sigma_parameters.f90
  smash/fcore/derived_type/mwd_setup.f90
  smash/fcore/derived_type/mwd_u_response_data.f90
  smash/fcore/external/lbfgsb.f
  smash/fcore/external/mwd_bayesian_tools.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/md_forward_structure.f90
  smash/fcore/optimize/mw_optimize.f90
  smash/fcore/optimize/mwd_cost.f90
  smash/fcore/routine/mwd_parameters_manipulation.f90
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_bayesian_optimize.py
  smash/tests/diff_baseline.csv
  smash/tests/test_constant.py
Labels: enhancement

#86 ENC_jobs_cmpt_tfm
  smash/_constant.py
  smash/core/model/model.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/run.py
  smash/fcore/derived_type/mwd_cost_options.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/optimize/mwd_cost.f90
  smash/fcore/signal_analysis/mwd_metrics.f90
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_optimize.py
  smash/tests/diff_baseline.csv
Labels: enhancement

#90 FIX: correct github link following the change of organization name
  README.md
  doc/source/conf.py
  doc/source/developers_guide/index.rst
  doc/source/getting_started/index.rst
  doc/source/release/0.4.1-notes.rst
  doc/source/release/0.5.0-notes.rst
  smash/core/simulation/options.py
Labels: maintenance

#91 ENC: Add auto wjreg
  smash/_constant.py
  smash/core/model/model.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/fcore/forward/forward_db.f90
  smash/fcore/optimize/mwd_cost.f90
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_optimize.py
  smash/tests/diff_baseline.csv
Labels: enhancement

#92 MAINT: Rename f90wrap_utils dir and dll
  f90wrap/finalize_f90wrap.py
  f90wrap/gen_py_mod_names.py
  f90wrap/kind_map
  f90wrap/py_mod_names
  makefile
  smash/factory/mesh/mesh.py
  smash/fcore/_f90wrap_decorator.py
Labels: maintenance

#93 MAINT: rename opr_parameters and opr_states
  doc/source/api_reference/principal_methods/model.rst
  doc/source/api_reference/principal_methods/simulation.rst
  f90wrap/py_mod_names
  makefile.dep
  smash/_constant.py
  smash/core/model/_build_model.py
  smash/core/model/_standardize.py
  smash/core/model/model.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/control.py
  smash/core/simulation/estimate/_tools.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/_standardize.py
  smash/core/simulation/run/run.py
  smash/factory/net/_loss.py
  smash/fcore/derived_type/mwd_control.f90
  smash/fcore/derived_type/mwd_optimize_options.f90
  smash/fcore/derived_type/mwd_output.f90
  smash/fcore/derived_type/mwd_parameters.f90
  smash/fcore/derived_type/mwd_returns.f90
  smash/fcore/derived_type/mwd_rr_parameters.f90
  smash/fcore/derived_type/mwd_rr_states.f90
  smash/fcore/derived_type/mwd_setup.f90
  smash/fcore/forward/forward.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/md_forward_structure.f90
  smash/fcore/forward/mw_forward.f90
  smash/fcore/optimize/md_regularization.f90
  smash/fcore/optimize/mw_optimize.f90
  smash/fcore/optimize/mwd_cost.f90
  smash/fcore/routine/mwd_parameters_manipulation.f90
  smash/io/model/model.py
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_optimize.py
  smash/tests/core/simulation/test_run.py
  smash/tests/diff_baseline.csv
  smash/tests/io/test_model_io.py
  smash/tests/test_constant.py
Labels: maintenance

#94 ENC: Add vic3l model structure and refactorize md_forward_structure
  makefile.dep
  smash/_constant.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/run.py
  smash/fcore/derived_type/mwd_output.f90
  smash/fcore/forward/forward.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/md_forward_structure.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/fcore/operator/md_vic3l_operator.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
  smash/tests/test_constant.py
Labels: enhancement

#95 MAINT: Add key to trigger or not the GR interception capacity adjustment
  smash/_constant.py
  smash/core/model/_build_model.py
  smash/core/model/_standardize.py
  smash/fcore/derived_type/mwd_setup.f90
  smash/fcore/routine/mw_interception_capacity.f90
Labels: maintenance

#97 ENC: enhance API documentation
  smash/core/model/model.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/core/simulation/control.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/run.py
  smash/factory/samples/samples.py
Labels: documentation

#98 MAINT: Update README.md
  README.md
Labels: maintenance
