Repository DassHydro/smash, pull requests merged in 2023-09, with the labels that each got.

#66 FIX: fix deprecated warning of pandas 0.2.1 on signatures and segmentation computation
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
Labels: bug, maintenance

#69 ENC: add multiset estimate (bayes_estimate deprecated)
  setup.py
  smash/__init__.py
  smash/core/model/model.py
  smash/core/simulation/estimate/__init__.py
  smash/core/simulation/estimate/_standardize.py
  smash/core/simulation/estimate/_tools.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/run.py
  smash/factory/net/net.py
  smash/factory/samples/samples.py
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_estimate.py
  smash/tests/diff_baseline.csv
Labels: enhancement

#71 MAINT: Remove cost_variant from model simulation Python interface
  smash/_constant.py
  smash/core/model/model.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/estimate/_tools.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/_standardize.py
  smash/core/simulation/run/run.py
Labels: maintenance

#73 FIX: Fix path to smash logo with light theme
  README.md
Labels: bug

#74 ENC: Start API documentation
  doc/Makefile
  doc/source/_ext/custom_options_directive.py
  doc/source/api_reference/index.rst
  doc/source/api_reference/principal_methods/model.rst
  doc/source/api_reference/principal_methods/signal_analysis.rst
  doc/source/api_reference/principal_methods/simulation.rst
  doc/source/api_reference/returned_objects/multiple_forward_run.rst
  doc/source/api_reference/returned_objects/multiple_optimize.rst
  doc/source/api_reference/returned_objects/precipitation_indices.rst
  doc/source/api_reference/returned_objects/samples.rst
  doc/source/api_reference/returned_objects/signatures.rst
  doc/source/api_reference/sub-packages/factory.rst
  doc/source/api_reference/sub-packages/io.rst
  doc/source/api_reference/sub-packages/net/add_activation.rst
  doc/source/api_reference/sub-packages/net/add_dense.rst
  doc/source/api_reference/sub-packages/net/add_dropout.rst
  doc/source/api_reference/sub-packages/net/add_scale.rst
  doc/source/api_reference/sub-packages/net/index.rst
  doc/source/gen_rst.py
  smash/core/model/model.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/estimate/_standardize.py
  smash/core/simulation/estimate/_tools.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/run.py
  smash/factory/mesh/mesh.py
  smash/factory/net/net.py
  smash/factory/samples/samples.py
  smash/io/mesh/mesh.py
  smash/io/model/model.py
  smash/io/setup/setup.py
Labels: documentation

#75 ENC: Complete parameters/returns docstring for API
  doc/source/api_reference/principal_methods/simulation.rst
  doc/source/gen_rst.py
  smash/__init__.py
  smash/_constant.py
  smash/core/model/model.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/estimate/_standardize.py
  smash/core/simulation/estimate/_tools.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/run.py
  smash/factory/mesh/mesh.py
  smash/factory/net/net.py
  smash/factory/samples/samples.py
Labels: documentation

#77 FIX: Update final states when using ANN mapping for regionalization
  smash/core/simulation/optimize/optimize.py
Labels: bug

#79 ENC/FIX: Finalize API structure and fix docstring
  doc/source/api_reference/index.rst
  doc/source/api_reference/principal_methods/simulation.rst
  doc/source/api_reference/returned_objects/index.rst
  doc/source/api_reference/returned_objects/multiple_forward_run.rst
  doc/source/api_reference/returned_objects/multiple_optimize.rst
  doc/source/api_reference/returned_objects/precipitation_indices.rst
  doc/source/api_reference/returned_objects/samples.rst
  doc/source/api_reference/returned_objects/signatures.rst
  doc/source/api_reference/sub-packages/factory.rst
  doc/source/api_reference/sub-packages/io.rst
  doc/source/api_reference/sub-packages/net/index.rst
  smash/core/model/model.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/run.py
  smash/factory/dataset/dataset.py
  smash/factory/mesh/mesh.py
  smash/factory/net/_layers.py
  smash/factory/net/net.py
  smash/factory/samples/samples.py
  smash/io/mesh/mesh.py
  smash/io/model/model.py
  smash/io/setup/setup.py
  smash/tests/core/signal_analysis/test_prcp_indices.py
  smash/tests/core/signal_analysis/test_signatures.py
  smash/tests/core/simulation/test_optimize.py
  smash/tests/core/simulation/test_run.py
Labels: documentation

#80 ENC/FIX: Enhance API doc and fix early_stopping for ann optimize
  doc/source/developers_guide/index.rst
  smash/_constant.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/factory/net/net.py
  smash/tests/core/simulation/test_run.py
Labels: documentation, enhancement

#81 FIX: fix bug when computing dflow for segmentation algo
  smash/core/signal_analysis/segmentation/_tools.py
Labels: bug

#83 * ENC: Add loieau model structure
  smash/_constant.py
  smash/fcore/forward/forward.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/md_forward_structure.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
  smash/tests/test_constant.py
Labels: enhancement

#82 ENC: Add optional returns options
  doc/source/api_reference/returned_objects/index.rst
  makefile.dep
  smash/__init__.py
  smash/_constant.py
  smash/core/model/_build_model.py
  smash/core/model/_read_input_data.py
  smash/core/model/model.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/estimate/_standardize.py
  smash/core/simulation/estimate/_tools.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/_standardize.py
  smash/core/simulation/run/run.py
  smash/fcore/common/m_array_manipulation.f90
  smash/fcore/common/m_screen_display.f90
  smash/fcore/derived_type/mwd_returns.f90
  smash/fcore/forward/forward.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/md_forward_structure.f90
  smash/fcore/optimize/mw_optimize.f90
  smash/fcore/optimize/mwd_cost.f90
  smash/fcore/routine/mwd_parameters_manipulation.f90
  smash/fcore/signal_analysis/mwd_signatures.f90
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_estimate.py
  smash/tests/core/simulation/test_optimize.py
  smash/tests/core/simulation/test_run.py
  smash/tests/diff_baseline.csv
  tapenade/makefile
Labels: enhancement, help wanted

#85 ENC: Add net for return options:
  smash/_constant.py
  smash/core/model/model.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/run.py
  smash/factory/net/net.py
Labels: documentation, enhancement
