Repository DassHydro/smash, pull requests merged in 2024-04, with the labels that each got.

#158 FIX: Beta parameter in GR percolation
  doc/source/user_guide/others/input_data_convention.rst
  doc/source/user_guide/quickstart/cance_first_simulation.rst
  smash/core/model/model.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_doc.py
  smash/core/simulation/options.py
  smash/fcore/forward/forward_db.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_estimate.py
  smash/tests/diff_baseline.csv
Labels: bug

#164 DOC: Add notes to explain smash dates convention
  doc/source/user_guide/quickstart/cance_first_simulation.rst
  doc/source/user_guide/quickstart/france_large_domain_simulation.rst
  smash/core/model/model.py
  smash/tests/core/test_read_input_data.py
Labels: documentation

#165 FIX: Handle missing values for interception capacity calculation
  doc/source/release/1.0.0-notes.rst
  smash/fcore/routine/mw_interception_capacity.f90
Labels: bug

#169 FIX: parameter order in bounds defined in scaling layer of net
  smash/core/simulation/_standardize.py
Labels: bug

#167 MAINT: Switch from gdal to rasterio
  .github/workflows/code-checks.yml
  .github/workflows/doc.yml
  .github/workflows/unit-tests.yml
  doc/source/release/1.0.0-notes.rst
  environment-dev.yml
  environment.yml
  requirements.txt
  smash/core/model/_build_model.py
  smash/core/model/_read_input_data.py
  smash/factory/mesh/_standardize.py
  smash/factory/mesh/_tools.py
  smash/factory/mesh/mesh.py
  smash/tests/test_define_global_vars.py
Labels: maintenance

#171 DOC: Fix user guide typo
  doc/source/user_guide/quickstart/lez_split_sample_test.rst
Labels: documentation

#172 ENH: Meson build system
  .github/workflows/code-checks.yml
  .github/workflows/doc.yml
  .github/workflows/unit-tests.yml
  .github/workflows/wheel.yml
  .gitignore
  Dockerfile
  MANIFEST.in
  Makefile
  dependencies.py
  environment-dev.yml
  environment.yml
  f90wrap/finalize_f90wrap.py
  f90wrap/gen_py_mod_names.py
  f90wrap/generate_f90wrap.py
  f90wrap/py_mod_names
  generate_version.py
  makefile
  makefile.dep
  meson.build
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  smash/__init__.py
  smash/factory/mesh/meson.build
  smash/fcore/_f90wrap_decorator.py
  smash/fcore/meson.build
  smash/meson.build
  tapenade/Makefile
  venv-dev.sh
  venv_install.sh
Labels: enhancement

#173 adapt venv_install.sh to install SMASH 1.0 with python-venv
  venv-dev.sh
  venv_install.sh
Labels: enhancement
