Repository DassHydro/smash, pull requests merged in 2024-07, with the labels that each got.

#216 ENH/MAINT: enhance metric computation method
  doc/source/api_reference/principal_methods/signal_analysis.rst
  doc/source/user_guide/classical_uses/lez_regionalization.rst
  doc/source/user_guide/quickstart/lez_split_sample_test.rst
  smash/__init__.py
  smash/core/signal_analysis/evaluation/__init__.py
  smash/core/signal_analysis/evaluation/_standardize.py
  smash/core/signal_analysis/evaluation/evaluation.py
  smash/core/signal_analysis/metrics/_standardize.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/tests/baseline.hdf5
  smash/tests/core/signal_analysis/test_evaluation.py
  smash/tests/core/simulation/test_estimate.py
  smash/tests/diff_baseline.csv
Labels: enhancement, maintenance

#241 Rebase of MJA pull request on main
  smash/_constant.py
  smash/core/model/_standardize.py
  smash/core/simulation/_standardize.py
  venv_install.sh
Labels: enhancement, maintenance

#245 Rebase of MJA pull request on main (#241)
  smash/_constant.py
  smash/core/model/_standardize.py
  smash/core/simulation/_standardize.py
  venv_install.sh
Labels: backport

#242 MAINT: macos py312 wheels
  .github/workflows/wheel.yml
  meson.build
  pyproject.toml
Labels: enhancement

#256 DOC: Add pypi badge for smash
  README.md
Labels: documentation

#258 MAINT: Sphinx v7.4 compatibility
  doc/Makefile
  doc/source/_ext/custom_options_directive.py
  doc/source/release/0.2.4-notes.rst
  doc/source/release/0.3.0-notes.rst
  doc/source/release/0.3.1-notes.rst
  doc/source/release/0.4.0-notes.rst
  doc/source/release/0.4.1-notes.rst
  doc/source/release/0.4.2-notes.rst
  doc/source/release/0.5.0-notes.rst
  doc/source/release/1.0.0-notes.rst
  doc/source/release/1.0.1-notes.rst
  doc/source/release/template-notes.rst
  environment-dev.yml
  pyproject.toml
  requirements-dev.txt
  smash/core/model/model.py
  smash/core/signal_analysis/evaluation/evaluation.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_doc.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/run.py
  smash/factory/samples/samples.py
  smash/io/model_ddt.py
Labels: maintenance

#259 MAINT: Sphinx v7.4 compatibility
  doc/Makefile
  doc/source/_ext/custom_options_directive.py
  doc/source/release/0.2.4-notes.rst
  doc/source/release/0.3.0-notes.rst
  doc/source/release/0.3.1-notes.rst
  doc/source/release/0.4.0-notes.rst
  doc/source/release/0.4.1-notes.rst
  doc/source/release/0.4.2-notes.rst
  doc/source/release/0.5.0-notes.rst
  doc/source/release/1.0.0-notes.rst
  doc/source/release/1.0.1-notes.rst
  doc/source/release/template-notes.rst
  environment-dev.yml
  pyproject.toml
  requirements-dev.txt
  smash/core/model/model.py
  smash/core/signal_analysis/metrics/metrics.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_doc.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/run.py
  smash/factory/samples/samples.py
  smash/io/model_ddt.py
Labels: backport

#261 MAINT: Add Python3.12 unit tests
  .github/workflows/unit-tests.yml
Labels: maintenance

#262 DOC: Add pypi badge for smash
  README.md
Labels: backport

#263 FIX: Check descriptor missing values on active cells
  smash/core/model/_read_input_data.py
Labels: bug

#264 DOC: Update contributor guide summary
  doc/source/contributor_guide/development_process_summary.rst
Labels: documentation

#268 FIX: scaling layer for bounded outputs from activation layer
  smash/factory/net/_layers.py
  smash/factory/net/_standardize.py
  smash/factory/net/net.py
Labels: bug

#269 FIX: Check descriptor missing valus on active cells
  smash/core/model/_read_input_data.py
Labels: backport

#270 DOC: Update contributor guide summary
  doc/source/contributor_guide/development_process_summary.rst
Labels: backport

#272 FIX: scaling layer from bounded outputs from activation layer
  smash/factory/net/_layers.py
  smash/factory/net/_standardize.py
  smash/factory/net/net.py
Labels: backport

#274 FIX: docstring serr_sigma_parameters
  smash/core/model/model.py
Labels: documentation

#232 Internal fluxes
  pyproject.toml
  smash/_constant.py
  smash/core/model/_standardize.py
  smash/core/simulation/_doc.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/run.py
  smash/fcore/derived_type/mwd_returns.f90
  smash/fcore/derived_type/mwd_setup.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/forward_openmp_db.f90
  smash/fcore/forward/md_simulation.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/fcore/operator/md_routing_operator.f90
  smash/fcore/operator/md_snow_operator.f90
  smash/fcore/operator/md_vic3l_operator.f90
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_internal_fluxes.py
  smash/tests/diff_baseline.csv
  smash/tests/test_constant.py
Labels: enhancement

#275 FIX: docstring serr_sigma_parameters (#274)
  smash/core/model/model.py
Labels: documentation, backport

#277 DOC: correct control_tfm documentation
  smash/core/simulation/_doc.py
Labels: documentation

#278 DOC: correct control_tfm documentation (#277)
  smash/core/simulation/_doc.py
Labels: documentation, backport

#280 Fix crash in generate mesh if a well is present at a cell
  smash/factory/mesh/mw_mesh.f90
Labels: bug

#281 Fix crash in generate mesh if a well is present at a cell : infinite recursive loop. Just test if it is a well and cycle
  smash/factory/mesh/mw_mesh.f90
Labels: backport

#284 DOC: add note to contributor guide for test-baseline (#283)
  doc/source/contributor_guide/development_process_details.rst
Labels: backport

#210 Exponential store gr6
  doc/source/_static/bib/references.bib
  doc/source/_static/gr6_structure.svg
  doc/source/math_num_documentation/forward_structure.rst
  smash/_constant.py
  smash/core/model/model.py
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/forward_openmp_db.f90
  smash/fcore/forward/md_simulation.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
  smash/tests/test_constant.py
Labels: enhancement

#287 ENH: set parameters condition outside active cell
  smash/_constant.py
  smash/core/model/_standardize.py
  smash/core/simulation/_doc.py
  smash/core/simulation/_standardize.py
  smash/fcore/forward/md_simulation.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/tests/test_constant.py
Labels: enhancement

#288 ENH: set parameters condition outside active cell
  smash/_constant.py
  smash/core/model/_standardize.py
  smash/core/simulation/_doc.py
  smash/core/simulation/_standardize.py
Labels: backport

#289 MAINT: v1.0.2 release note
  doc/source/release/1.0.2-notes.rst
  doc/source/release/index.rst
Labels: maintenance
