Repository DassHydro/smash, pull requests merged in 2024-09, with the labels that each got.

#294 ENH: new hybrid hydrological models using neural network and ODE-based system
  doc/source/api_reference/fortran/index.rst
  doc/source/api_reference/principal_methods/model.rst
  smash/__init__.py
  smash/_constant.py
  smash/core/model/_build_model.py
  smash/core/model/_standardize.py
  smash/core/model/model.py
  smash/core/signal_analysis/segmentation/_tools.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_doc.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/factory/net/_loss.py
  smash/factory/net/net.py
  smash/factory/samples/_standardize.py
  smash/fcore/common/md_algebra.f90
  smash/fcore/derived_type/mwd_control.f90
  smash/fcore/derived_type/mwd_nn_parameters.f90
  smash/fcore/derived_type/mwd_optimize_options.f90
  smash/fcore/derived_type/mwd_parameters.f90
  smash/fcore/derived_type/mwd_setup.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/forward_openmp_db.f90
  smash/fcore/forward/md_simulation.f90
  smash/fcore/meson.build
  smash/fcore/operator/md_gr_operator.f90
  smash/fcore/operator/md_neural_network.f90
  smash/fcore/routine/mwd_parameters_manipulation.f90
  smash/io/model_ddt.py
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_bayesian_optimize.py
  smash/tests/core/simulation/test_optimize.py
  smash/tests/core/simulation/test_run.py
  smash/tests/diff_baseline.csv
  smash/tests/test_constant.py
Labels: enhancement

#298 Check well in flwdir
  doc/source/user_guide/quickstart/cance_first_simulation.rst
  smash/factory/dataset/France_flwdir.tif
  smash/factory/mesh/_standardize.py
  smash/factory/mesh/mesh.py
  smash/factory/mesh/mw_mesh.f90
  smash/fcore/routine/mw_mask.f90
Labels: bug

#308 FIX: fix baseline and add minor corrections to previous PRs
  smash/core/simulation/_doc.py
  smash/core/simulation/optimize/optimize.py
  smash/factory/mesh/mesh.py
  smash/factory/mesh/mw_mesh.f90
  smash/tests/generate_baseline.py
Labels: maintenance

#312 ENH: new methods added to `smash.factory.Net`
  doc/source/api_reference/sub-packages/factory.rst
  smash/core/model/model.py
  smash/core/simulation/_doc.py
  smash/factory/net/_layers.py
  smash/factory/net/_standardize.py
  smash/factory/net/net.py
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
  smash/tests/factory/test_net.py
Labels: enhancement

#313 ENH: Add grc structure based on MJA dev
  doc/source/_static/grc_structure.svg
  doc/source/_static/grd_structure.svg
  doc/source/math_num_documentation/forward_structure.rst
  smash/_constant.py
  smash/core/model/model.py
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/forward_openmp_db.f90
  smash/fcore/forward/md_simulation.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
  smash/tests/test_constant.py
Labels: enhancement

#315 ENH: add adaptive optimizers for all mappings
  doc/source/math_num_documentation/forward_structure.rst
  doc/source/user_guide/classical_uses/lez_regionalization.rst
  doc/source/user_guide/quickstart/cance_first_simulation.rst
  smash/_constant.py
  smash/core/model/_standardize.py
  smash/core/signal_analysis/evaluation/evaluation.py
  smash/core/simulation/_doc.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/control.py
  smash/core/simulation/estimate/_tools.py
  smash/core/simulation/estimate/estimate.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/_tools.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/options.py
  smash/core/simulation/run/run.py
  smash/factory/net/_layers.py
  smash/factory/net/_loss.py
  smash/factory/net/net.py
  smash/fcore/external/lbfgsb.f
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/forward_openmp_db.f90
  smash/fcore/meson.build
  smash/fcore/routine/mwd_parameters_manipulation.f90
  smash/tests/baseline.hdf5
  smash/tests/core/signal_analysis/test_signatures.py
  smash/tests/core/simulation/test_optimize.py
  smash/tests/diff_baseline.csv
Labels: bug, documentation, enhancement

#318 ENH: add callback signature for optimize method
  smash/core/model/model.py
  smash/core/simulation/_doc.py
  smash/core/simulation/control.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/factory/net/net.py
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_optimize.py
  smash/tests/diff_baseline.csv
Labels: documentation, enhancement

#320 MAINT: remove cost options control info
  smash/core/simulation/_doc.py
  smash/core/simulation/control.py
Labels: maintenance

#321 MAINT: change the default NN for ANN-based regionalization
  doc/source/user_guide/classical_uses/lez_regionalization.rst
  smash/core/simulation/_standardize.py
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
Labels: maintenance

#323 FIX: Rounding error with array slice with lat-lon raster
  smash/core/model/_read_input_data.py
Labels: bug

#324 FIX: Fix the exchange term in gr6/grc svg structure
  doc/source/_static/gr6_structure.svg
  doc/source/_static/grc_structure.svg
  smash/core/model/model.py
Labels: bug, documentation

#322 ENH: retrieve model parameters from control vector value
  doc/source/api_reference/principal_methods/model.rst
  smash/core/model/model.py
  smash/core/simulation/_doc.py
  smash/core/simulation/optimize/_tools.py
  smash/core/simulation/optimize/optimize.py
  smash/factory/net/_loss.py
  smash/factory/net/net.py
Labels: enhancement

#331 FIX: reset random seed after setting random_state
  smash/core/model/model.py
  smash/core/simulation/optimize/_tools.py
  smash/factory/net/net.py
  smash/factory/samples/samples.py
Labels: bug

#326 FIX: Update sink detection
  doc/generate_dataset.py
  doc/source/api_reference/sub-packages/factory.rst
  doc/source/user_guide/quickstart/cance_first_simulation.rst
  smash/factory/__init__.py
  smash/factory/mesh/_standardize.py
  smash/factory/mesh/mesh.py
  smash/factory/mesh/mw_mesh.f90
  smash/fcore/routine/mw_mask.f90
  smash/tests/factory/test_mesh.py
Labels: enhancement

#332 ENH: add n_iter key for callback and return_options optimize
  smash/_constant.py
  smash/core/simulation/_doc.py
  smash/core/simulation/optimize/optimize.py
  smash/factory/net/net.py
Labels: enhancement
