Repository DassHydro/smash, pull requests merged in 2024-01, with the labels that each got.

#120 MAINT: Update the color of the corporate logo
  doc/source/_static/corporate_logo.svg
  doc/source/_static/corporate_logo_dark.svg
Labels: maintenance

#121 DOC/FIX: Update the math/num documentation and fix in vic3l
  doc/source/_static/bib/references.bib
  doc/source/_static/diagram_gr-a.png
  doc/source/_static/diagram_gr-b.png
  doc/source/_static/diagram_gr-c.png
  doc/source/_static/diagram_gr-d.png
  doc/source/_static/flwdir_flwacc_Practice_case.png
  doc/source/_static/hydrological_module.svg
  doc/source/_static/model_description.svg
  doc/source/_static/real_case_cance_catchment.png
  doc/source/_static/routing_module.svg
  doc/source/_static/snow_module.svg
  doc/source/gen_rst.py
  doc/source/index.rst
  doc/source/math_num_documentation/forward/forward_problem_statement.rst
  doc/source/math_num_documentation/forward/hydrological_operators.rst
  doc/source/math_num_documentation/forward/regionalization_operators.rst
  doc/source/math_num_documentation/forward_inverse_problem.rst
  doc/source/math_num_documentation/forward_structure.rst
  doc/source/math_num_documentation/index.rst
  doc/source/math_num_documentation/inverse/algorithms.rst
  doc/source/math_num_documentation/inverse/inverse_problem_statement.rst
  doc/source/math_num_documentation/mapping.rst
  doc/source/math_num_documentation/signal_analysis/cost_functions.rst
  doc/source/math_num_documentation/signal_analysis/hydrograph_segmentation.rst
  doc/source/math_num_documentation/signal_analysis/hydrological_signatures.rst
  smash/fcore/derived_type/mwd_u_response_data.f90
  smash/fcore/external/mwd_bayesian_tools.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/fcore/operator/md_vic3l_operator.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
Labels: bug, documentation

#124 ENC: complete initialization section for ANN mapping in Math Num Doc
  doc/source/_static/FCNN.png
  doc/source/math_num_documentation/mapping.rst
Labels: documentation

#122 DOC: Add metric prcp partitioning segmentation and sign in math/num
  doc/source/math_num_documentation/efficiency_error_metric.rst
  doc/source/math_num_documentation/forward_structure.rst
  doc/source/math_num_documentation/hydrograph_segmentation.rst
  doc/source/math_num_documentation/hydrological_signatures.rst
  doc/source/math_num_documentation/index.rst
  doc/source/math_num_documentation/precipitation_partitioning.rst
Labels: documentation

#126 DOC: Add contributor guide
  doc/source/contributor_guide/bug_report_and_enhancement_requests.rst
  doc/source/contributor_guide/development_process_details.rst
  doc/source/contributor_guide/development_process_summary.rst
  doc/source/contributor_guide/index.rst
  doc/source/contributors/index.rst
  doc/source/developers_guide/index.rst
  doc/source/index.rst
Labels: documentation

#131 DOC: Cance and France Quickstart
  .gitignore
  doc/gen_dataset.py
  doc/source/_static/cance.png
  doc/source/_static/france.png
  doc/source/user_guide/index.rst
  doc/source/user_guide/quickstart/cance_first_simulation.rst
  doc/source/user_guide/quickstart/france_large_domain_simulation.rst
  smash/core/simulation/_standardize.py
  smash/factory/dataset/Cance/gauge_attributes.csv
  smash/factory/dataset/Cance/mesh_Cance.py
  smash/factory/dataset/Cance/qobs/V3504010.csv
  smash/factory/dataset/France/mesh_France.py
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010000_201201010000.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010100_201201010100.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010200_201201010200.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010300_201201010300.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010400_201201010400.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010500_201201010500.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010600_201201010600.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010700_201201010700.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010800_201201010800.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201010900_201201010900.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011000_201201011000.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011100_201201011100.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011200_201201011200.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011300_201201011300.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011400_201201011400.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011500_201201011500.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011600_201201011600.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011700_201201011700.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011800_201201011800.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201011900_201201011900.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201012000_201201012000.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201012100_201201012100.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201012200_201201012200.tif
  smash/factory/dataset/France/prcp/2012/01/01/antilope_j1_000100_201201012300_201201012300.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020000_201201020000.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020100_201201020100.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020200_201201020200.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020300_201201020300.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020400_201201020400.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020500_201201020500.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020600_201201020600.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020700_201201020700.tif
  smash/factory/dataset/France/prcp/2012/01/02/antilope_j1_000100_201201020800_201201020800.tif
  smash/factory/dataset/Lez/gauge_attributes.csv
  smash/factory/dataset/Lez/mesh_Lez.py
  smash/io/mesh.py
  smash/io/setup.py
Labels: documentation

#134 DOC: User Guide Split sample test
  doc/source/_static/lez.png
  doc/source/user_guide/index.rst
  doc/source/user_guide/quickstart/france_large_domain_simulation.rst
  doc/source/user_guide/quickstart/lez_split_sample_test.rst
Labels: documentation

#135 DOC: Add input data convention
  doc/source/_static/daily_pet_ratio.png
  doc/source/math_num_documentation/cost_function.rst
  doc/source/user_guide/index.rst
  doc/source/user_guide/others/input_data_convention.rst
  smash/core/model/model.py
  smash/core/signal_analysis/prcp_indices/prcp_indices.py
  smash/core/signal_analysis/segmentation/segmentation.py
  smash/core/signal_analysis/signatures/signatures.py
  smash/core/simulation/_doc.py
  smash/factory/mesh/mesh.py
Labels: documentation

#136 DOC: Clean user guide and repo
  doc/mesh.hdf5
  doc/model.hdf5
  doc/setup.yaml
  doc/source/savefig/user_guide.classical_uses.lez_regionalization.ann_J.png
  doc/source/savefig/user_guide.classical_uses.lez_regionalization.ann_theta.png
  doc/source/savefig/user_guide.classical_uses.lez_regionalization.mp_theta.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.active_cell.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.flwacc.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.flwdir.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.flwdst.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.flwpar.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.forward_run_q.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.gauge_position.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.ma_prcp.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.mean_prcp_pet.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.model_flwdir.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.my_prcp.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.optimize_q.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.prcp.png
  doc/source/savefig/user_guide.quickstart.cance_first_simulation.qobs.png
  doc/source/savefig/user_guide.quickstart.france_large_domain_simulation.flwacc.png
  doc/source/savefig/user_guide.quickstart.france_large_domain_simulation.flwdir.png
  doc/source/savefig/user_guide.quickstart.france_large_domain_simulation.forward_run_q.png
  doc/source/savefig/user_guide.quickstart.france_large_domain_simulation.forward_run_q2.png
  doc/source/savefig/user_guide.quickstart.lez_split_sample_test.flwacc.png
  doc/source/savefig/user_guide.quickstart.lez_split_sample_test.flwdst.png
  doc/source/savefig/user_guide.quickstart.lez_split_sample_test.forward_run_q.png
  doc/source/savefig/user_guide.quickstart.lez_split_sample_test.gauge_position.png
  doc/source/savefig/user_guide.quickstart.lez_split_sample_test.optimize_q.png
  doc/source/user_guide/classical_uses/lez_regionalization.rst
  doc/source/user_guide/quickstart/cance_first_simulation.rst
  doc/source/user_guide/quickstart/france_large_domain_simulation.rst
  doc/source/user_guide/quickstart/lez_split_sample_test.rst
Labels: documentation
