Repository DassHydro/smash, pull requests merged in 2024-06, with the labels that each got.

#205 Doc graphes
  .gitignore
  doc/source/_static/Inversion_process_flowchart.png
  doc/source/_static/bib/references.bib
  doc/source/_static/css/smash.css
  doc/source/_static/flowchart_forward_gridded.png
  doc/source/_static/forward_composition_flowchart.png
  doc/source/_static/forward_simple_flowchart.png
  doc/source/asset/eqs_smash_doc.lyx
  doc/source/asset/smash_graphes_structures.odp
  doc/source/index.rst
  doc/source/math_num_documentation/forward_inverse_problem.rst
  doc/source/math_num_documentation/forward_structure.rst
  doc/source/math_num_documentation/index.rst
Labels: documentation

#203 FIX: Fix generate baseline
  Makefile
  smash/tests/generate_baseline.py
Labels: bug

#194 Fix directory path max length
  smash/fcore/derived_type/mwd_setup.f90
Labels: bug

#206 FIX PR: Add check and test on char maximum limit
  smash/fcore/_f90wrap_decorator.py
  smash/tests/fcore/test_f90wrap_decorator.py
Labels: maintenance

#208 Maintenance/1.0.x
  .gitignore
  Makefile
  doc/source/_static/Inversion_process_flowchart.png
  doc/source/_static/bib/references.bib
  doc/source/_static/css/smash.css
  doc/source/_static/flowchart_forward_gridded.png
  doc/source/_static/forward_composition_flowchart.png
  doc/source/_static/forward_simple_flowchart.png
  doc/source/asset/eqs_smash_doc.lyx
  doc/source/asset/smash_graphes_structures.odp
  doc/source/index.rst
  doc/source/math_num_documentation/forward_inverse_problem.rst
  doc/source/math_num_documentation/forward_structure.rst
  doc/source/math_num_documentation/index.rst
  doc/source/user_guide/classical_uses/lez_regionalization.rst
  doc/source/user_guide/quickstart/cance_first_simulation.rst
  doc/source/user_guide/quickstart/france_large_domain_simulation.rst
  doc/source/user_guide/quickstart/lez_split_sample_test.rst
  smash/fcore/_f90wrap_decorator.py
  smash/fcore/derived_type/mwd_mesh.f90
  smash/fcore/derived_type/mwd_setup.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/forward_openmp_db.f90
  smash/fcore/forward/md_simulation.f90
  smash/tests/fcore/test_f90wrap_decorator.py
  smash/tests/generate_baseline.py
Labels: maintenance

#220 MAINT: numpy 2.0 support
  environment-dev.yml
  pyproject.toml
  requirements-dev.txt
  smash/factory/mesh/_tools.py
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
  smash/tests/generate_baseline.py
Labels: maintenance

#214 DOC: upgrade math num section
  .gitignore
  doc/source/_static/flowchart_forward_gridded.png
  doc/source/_static/forward_composition_flowchart.png
  doc/source/_static/forward_flowchart_detail_input_params_states_fluxes.png
  doc/source/_static/forward_simple_flowchart.png
  doc/source/_static/gr4_structure.svg
  doc/source/_static/gr5_structure.svg
  doc/source/_static/grd_structure.svg
  doc/source/_static/loieau_structure.svg
  doc/source/_static/vic3l_structure.svg
  doc/source/asset/eqs_smash_doc.lyx
  doc/source/asset/smash_graphes_structures.odp
  doc/source/math_num_documentation/forward_inverse_problem.rst
  doc/source/math_num_documentation/forward_structure.rst
Labels: documentation

#226 FIX: fix code check with some bugs detected by ruff 0.5
  smash/core/simulation/_standardize.py
  smash/io/handler/_hdf5_handler.py
  smash/tests/core/simulation/test_bayesian_optimize.py
  smash/tests/core/simulation/test_optimize.py
Labels: bug

#225 MAINT: update pyproject.toml for compatibility with numpy 2
  doc/source/contributor_guide/development_process_details.rst
  environment-dev.yml
  pyproject.toml
  requirements-dev.txt
Labels: documentation, maintenance

#222 FIX: VIC3L under and over flow
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/forward_openmp_db.f90
  smash/fcore/operator/md_vic3l_operator.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
Labels: bug

#227 MAINT: release note 1.0.1
  doc/source/release/1.0.1-notes.rst
  doc/source/release/index.rst
Labels: maintenance

#229 Maintenance/1.0.x
  .gitignore
  doc/source/_static/flowchart_forward_gridded.png
  doc/source/_static/forward_composition_flowchart.png
  doc/source/_static/forward_flowchart_detail_input_params_states_fluxes.png
  doc/source/_static/forward_simple_flowchart.png
  doc/source/_static/gr4_structure.svg
  doc/source/_static/gr5_structure.svg
  doc/source/_static/grd_structure.svg
  doc/source/_static/loieau_structure.svg
  doc/source/_static/vic3l_structure.svg
  doc/source/asset/eqs_smash_doc.lyx
  doc/source/asset/smash_graphes_structures.odp
  doc/source/contributor_guide/development_process_details.rst
  doc/source/math_num_documentation/forward_inverse_problem.rst
  doc/source/math_num_documentation/forward_structure.rst
  doc/source/release/1.0.1-notes.rst
  doc/source/release/index.rst
  environment-dev.yml
  pyproject.toml
  requirements-dev.txt
  smash/core/simulation/_standardize.py
  smash/factory/mesh/_tools.py
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/forward_openmp_db.f90
  smash/fcore/operator/md_vic3l_operator.f90
  smash/io/handler/_hdf5_handler.py
  smash/tests/baseline.hdf5
  smash/tests/core/simulation/test_bayesian_optimize.py
  smash/tests/core/simulation/test_optimize.py
  smash/tests/diff_baseline.csv
  smash/tests/generate_baseline.py
Labels: maintenance
