Repository DassHydro/smash, pull requests merged in 2024-08, with the labels that each got.

#293 manage kernel pip
  doc/source/getting_started/index.rst
Labels: documentation

#296 DOC: Update getting started installation
  doc/source/getting_started/index.rst
Labels: documentation

#297 manage kernel pip
  doc/source/getting_started/index.rst
Labels: documentation, backport

#299 MAINT: Update release note
  doc/source/release/1.0.2-notes.rst
Labels: maintenance

#300 MAINT: Update release note
  doc/source/release/1.0.2-notes.rst
Labels: maintenance, backport
