Repository DassHydro/smash, pull requests merged in 2024-11, with the labels that each got.

#342 FIX: checking control size in case of ANN
  smash/core/model/model.py
  smash/core/simulation/optimize/_tools.py
Labels: bug

#346 MAINT: Switch to macOS-13 env
  .github/workflows/wheel.yml
Labels: maintenance

#350 Fix: initialise wjreg_fast before return the result
  smash/core/simulation/optimize/_tools.py
  smash/core/simulation/optimize/optimize.py
Labels: enhancement

#352 ENH: add test to check the forward pass of default hybrid structures
  smash/tests/core/simulation/test_run.py
Labels: enhancement
