Repository DassHydro/smash, pull requests merged in 2024-03, with the labels that each got.

#145 ENH: Low memory adjoint
  doc/source/contributor_guide/development_process_details.rst
  doc/source/math_num_documentation/hydrological_signature.rst
  f90wrap/finalize_f90wrap.py
  makefile.dep
  smash/_constant.py
  smash/core/model/_standardize.py
  smash/core/model/model.py
  smash/core/simulation/_standardize.py
  smash/factory/dataset/dataset.py
  smash/fcore/derived_type/md_checkpoint_variable.f90
  smash/fcore/derived_type/mwd_mesh.f90
  smash/fcore/derived_type/mwd_returns.f90
  smash/fcore/derived_type/mwd_setup.f90
  smash/fcore/forward/forward_db.f90
  smash/fcore/forward/md_simulation.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/fcore/operator/md_routing_operator.f90
  smash/fcore/operator/md_snow_operator.f90
  smash/fcore/operator/md_vic3l_operator.f90
  smash/fcore/routine/mw_atmos_statistic.f90
  smash/fcore/routine/mw_interception_capacity.f90
  smash/fcore/routine/mwd_atmos_manipulation.f90
  smash/fcore/routine/mwd_sparse_matrix_manipulation.f90
  smash/tests/test_constant.py
Labels: enhancement

#146 FIX: Fix a bug when the csv file of qobs start or end with start_time or end_time
  smash/core/model/_read_input_data.py
Labels: bug

#147 MAINT: Add v1.0 Release note
  doc/source/conf.py
  doc/source/contributor_guide/development_process_details.rst
  doc/source/release/1.0.0-notes.rst
Labels: maintenance

#148 MAINT: Update README.md
  README.md
Labels: maintenance

#149 FIX: Change percolation value for grd hydrological module
  smash/fcore/forward/forward_db.f90
  smash/fcore/operator/md_gr_operator.f90
  smash/tests/baseline.hdf5
  smash/tests/diff_baseline.csv
Labels: bug

#150 MAINT: Update github actions to use Node.js 20
  .github/workflows/code-checks.yml
  .github/workflows/doc.yml
  .github/workflows/unit-tests.yml
Labels: maintenance

#154 FIX/ENH: fix error in ann optim for initial state + enhance release note
  doc/source/release/1.0.0-notes.rst
  smash/core/model/model.py
  smash/core/simulation/optimize/optimize.py
  smash/factory/net/_loss.py
Labels: bug, documentation

#156 FIX: Min Max computation for physiographic descriptor
  doc/source/release/1.0.0-notes.rst
  smash/core/model/_read_input_data.py
Labels: bug
