Repository DassHydro/smash, pull requests merged in 2025-07, with the labels that each got.

#452 MAINT: fix import-outside-top-level for latest ruff version
  pyproject.toml
Labels: maintenance

#456 Prepare for release v1.1.2 (#454)
  doc/source/_static/versions.json
  doc/source/release/1.1.2-notes.rst
  doc/source/release/index.rst
Labels: backport

#432 The interception reservoir capacities can be now calibrated after the model creation
  doc/source/api_reference/principal_methods/model.rst
  smash/core/model/_build_model.py
  smash/core/model/model.py
Labels: enhancement

#459 The interception reservoir capacities can be now calibrated after the model creation (#432) by @maximejay
  doc/source/api_reference/principal_methods/model.rst
  smash/core/model/_build_model.py
  smash/core/model/model.py
Labels: backport
