Repository DassHydro/smash, pull requests merged in 2025-05, with the labels that each got.

#410 DOC: how to cite smash
  CITATIONS.rst
  LICENSE
  README.md
  README.rst
  doc/source/citations/index.rst
  doc/source/index.rst
  doc/source/math_num_documentation/index.rst
  doc/source/release/index.rst
  doc/source/user_guide/in_depth/hybrid_model_structures.rst
  doc/source/user_guide/in_depth/hybrid_model_strutures.rst
  doc/source/user_guide/index.rst
  pyproject.toml
  smash.bib
Labels: documentation, enhancement

#413 DOC/ENH: add math/num descriptions for hybrid flux correction structures
  doc/source/math_num_documentation/forward_structure.rst
Labels: documentation

#412 DOC/ENH: add tuto for advanced regionalization with NNs
  doc/source/_static/user_guide.in_depth.advanced_learnable_regionalization.cnn_theta.png
  doc/source/_static/user_guide.in_depth.advanced_learnable_regionalization.mlp_cnn_J.png
  doc/source/_static/user_guide.in_depth.advanced_learnable_regionalization.mlp_theta.png
  doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
  doc/source/user_guide/files_with_code_block.csv
  doc/source/user_guide/in_depth/advanced_learnable_regionalization.rst
Labels: documentation

#419 MAINT/FIX: remove This Page header doc smash
  doc/source/_static/css/smash.css
Labels: maintenance

#420 MAINT/FIX: remove This Page header doc smash (#419)
  doc/source/_static/css/smash.css
Labels: backport

#422 Add DOI badge to README (#421)
  README.md
Labels: backport

#418 DOC: add user guide tutorial on spatially distributed calibration
  doc/source/_static/user_guide.classical_uses.fully_distributed_calibration.hydrograph_model_d.png
  doc/source/_static/user_guide.classical_uses.fully_distributed_calibration.hydrograph_model_u.png
  doc/source/_static/user_guide.classical_uses.fully_distributed_calibration.params_model_d.png
  doc/source/_static/user_guide.in_depth.advanced_learnable_regionalization.cnn_theta.png
  doc/source/_static/user_guide.in_depth.advanced_learnable_regionalization.mlp_theta.png
  doc/source/math_num_documentation/mapping.rst
  doc/source/user_guide/classical_uses/fully_distributed_calibration.rst
  doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
  doc/source/user_guide/files_with_code_block.csv
  doc/source/user_guide/in_depth/hybrid_process_parameterization.rst
  doc/source/user_guide/quickstart/hydrological_mesh_construction.rst
  doc/source/user_guide/quickstart/model_object_initialization.rst
Labels: documentation

#427 DOC: add user guide tutorial on spatially distributed calibration (#418) by PAG
  doc/source/_static/user_guide.classical_uses.fully_distributed_calibration.hydrograph_model_d.png
  doc/source/_static/user_guide.classical_uses.fully_distributed_calibration.hydrograph_model_u.png
  doc/source/_static/user_guide.classical_uses.fully_distributed_calibration.params_model_d.png
  doc/source/_static/user_guide.in_depth.advanced_learnable_regionalization.cnn_theta.png
  doc/source/_static/user_guide.in_depth.advanced_learnable_regionalization.mlp_theta.png
  doc/source/math_num_documentation/mapping.rst
  doc/source/user_guide/classical_uses/fully_distributed_calibration.rst
  doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
  doc/source/user_guide/files_with_code_block.csv
  doc/source/user_guide/in_depth/hybrid_process_parameterization.rst
  doc/source/user_guide/quickstart/hydrological_mesh_construction.rst
  doc/source/user_guide/quickstart/model_object_initialization.rst
Labels: backport
