Repository DassHydro/smash, pull requests merged in 2025-02, with the labels that each got.

#373 Doc hydro signatures
  doc/source/user_guide/classical_uses/hydrological_signatures.rst
Labels: documentation

#374 DOC: change of user guide order/title and fix tutos in classical uses section
  doc/source/user_guide/classical_uses/classical_calibration_io.rst
  doc/source/user_guide/classical_uses/hydrograph_segmentation.rst
  doc/source/user_guide/classical_uses/large_domain_simulation.rst
  doc/source/user_guide/classical_uses/rainfall_indices.rst
  doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
  doc/source/user_guide/classical_uses/split_sample_temporal_validation.rst
  doc/source/user_guide/classical_uses/working_with_your_own_data.rst
  doc/source/user_guide/in_depth/control_parameters_manipulation.rst
  doc/source/user_guide/in_depth/lat_long_data.rst
  doc/source/user_guide/in_depth/retrieving_control_parameters.rst
  doc/source/user_guide/index.rst
  doc/source/user_guide/quickstart/input_data_model_initialization.rst
  smash/core/model/model.py
Labels: documentation

#377 DOC: external tool - sensitivity analysis
  doc/source/user_guide/external_tools/sensitivity_analysis.rst
Labels: documentation, enhancement

#386 MAINT: update ruff format with new version
  generate_version.py
  smash/core/model/_read_input_data.py
  smash/core/model/_standardize.py
  smash/core/model/model.py
  smash/core/simulation/optimize/optimize.py
  smash/core/simulation/run/_standardize.py
  smash/factory/mesh/_tools.py
  smash/factory/net/net.py
  smash/tests/core/simulation/test_bayesian_optimize.py
  smash/tests/core/simulation/test_estimate.py
  smash/tests/core/simulation/test_optimize.py
  smash/tests/core/simulation/test_run.py
  smash/tests/core/test_read_input_data.py
  smash/tests/factory/test_net.py
  smash/tests/io/test_model_io.py
Labels: maintenance

#385 ENH/DOC: add automatic output code block generation, improve contributor guide
  doc/source/contributor_guide/development_process_details.rst
  doc/source/user_guide/files_with_code_block.csv
  doc/source/user_guide/post_processing_external_tools/sensitivity_analysis.rst
  doc/source/user_guide/pyexec_rst.py
Labels: documentation, enhancement

#387 MAINT/ENH: enhance user guide writing method
  doc/Makefile
  doc/source/_static/user_guide.classical_uses.regionalization_spatial_validation.ann_J.png
  doc/source/_static/user_guide.classical_uses.regionalization_spatial_validation.ann_theta.png
  doc/source/_static/user_guide.classical_uses.regionalization_spatial_validation.ml_theta.png
  doc/source/_static/user_guide.classical_uses.split_sample_temporal_validation.forward_run_q.png
  doc/source/_static/user_guide.classical_uses.split_sample_temporal_validation.optimize_q.png
  doc/source/_static/user_guide.in_depth.multicriteria_calibration.hydrograph.png
  doc/source/_static/user_guide.quickstart.forward_run_classical_calibration.forward_run_q.png
  doc/source/_static/user_guide.quickstart.forward_run_classical_calibration.optimize_q.png
  doc/source/contributor_guide/development_process_details.rst
  doc/source/user_guide/classical_uses/hydrograph_segmentation.rst
  doc/source/user_guide/classical_uses/hydrological_signatures.rst
  doc/source/user_guide/classical_uses/large_domain_simulation.rst
  doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
  doc/source/user_guide/classical_uses/split_sample_temporal_validation.rst
  doc/source/user_guide/data_and_format_description/cance.rst
  doc/source/user_guide/data_and_format_description/format_description.rst
  doc/source/user_guide/data_and_format_description/france.rst
  doc/source/user_guide/data_and_format_description/lez.rst
  doc/source/user_guide/files_with_code_block.csv
  doc/source/user_guide/in_depth/multicriteria_calibration.rst
  doc/source/user_guide/index.rst
  doc/source/user_guide/post_processing_external_tools/sensitivity_analysis.rst
  doc/source/user_guide/pyexec_rst.py
  doc/source/user_guide/quickstart/forward_run_classical_calibration.rst
  doc/source/user_guide/quickstart/hydrological_mesh_construction.rst
  doc/source/user_guide/quickstart/model_object_initialization.rst
Labels: documentation, enhancement, maintenance

#390 MAINT: directly remove generated files when compiling doc
  .gitignore
  doc/Makefile
  doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
  doc/source/user_guide/quickstart/forward_run_classical_calibration.rst
  doc/source/user_guide/quickstart/hydrological_mesh_construction.rst
  doc/source/user_guide/quickstart/model_object_initialization.rst
Labels: documentation, maintenance

#394 Remove autosummary sphinx extension
  doc/source/conf.py
Labels: bug

#395 MAINT: Remove sphinx-autosummary-accessors from smash dependencies
  environment-dev.yml
  pyproject.toml
  requirements-dev.txt
Labels: maintenance

#396 ENH: Dynamic variables for Python versions in documentation
  doc/source/conf.py
  doc/source/getting_started/index.rst
  pyproject.toml
Labels: enhancement

#392 DOC: add user guide retrieving control
  doc/source/user_guide/files_with_code_block.csv
  doc/source/user_guide/in_depth/retrieving_control_parameters.rst
Labels: documentation
