Repository DassHydro/smash, pull requests merged in 2025-06, with the labels that each got.

#434 MAINT: Temporarily drop windows support
  .github/workflows/wheel.yml
  doc/source/getting_started/index.rst
Labels: maintenance

#424 Doc: add tutoriel for distributed calibration with regularisation
  doc/source/_static/bib/references.bib
  doc/source/_static/user_guide.in_depth.calibration_with_regularisation_term.calibrated_cp_lcurve_hard_smoothing.png
  doc/source/_static/user_guide.in_depth.calibration_with_regularisation_term.calibrated_cp_reg.png
  doc/source/_static/user_guide.in_depth.calibration_with_regularisation_term.calibrated_cp_reg_lcurve.png
  doc/source/_static/user_guide.in_depth.calibration_with_regularisation_term.calibrated_noreg.png
  doc/source/_static/user_guide.in_depth.calibration_with_regularisation_term.hydrograph_noreg.png
  doc/source/_static/user_guide.in_depth.calibration_with_regularisation_term.hydrograph_reg.png
  doc/source/_static/user_guide.in_depth.calibration_with_regularisation_term.hydrograph_reg_lcurve.png
  doc/source/_static/user_guide.in_depth.calibration_with_regularisation_term.lcurve.png
  doc/source/user_guide/files_with_code_block.csv
  doc/source/user_guide/in_depth/bayesian_estimation.rst
  doc/source/user_guide/in_depth/calibration_with_regularization_term.rst
  doc/source/user_guide/in_depth/multicriteria_calibration.rst
Labels: documentation

#435 MAINT: Temporarily drop windows support (#434)
  .github/workflows/wheel.yml
  doc/source/getting_started/index.rst
Labels: backport

#429 MAINT: Add dynamic version switcher using external JSON file
  doc/source/_static/css/smash.css
  doc/source/_static/versions.json
  doc/source/_templates/navbar-nav.html
  doc/source/conf.py
Labels: maintenance

#437 ENH: Add gradient-free optimizers (nelder-mead and powell) (#425)
  doc/source/_static/bib/references.bib
  doc/source/math_num_documentation/index.rst
  doc/source/math_num_documentation/optimization_algorithms.rst
  doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
  doc/source/user_guide/classical_uses/split_sample_temporal_validation.rst
  doc/source/user_guide/quickstart/forward_run_classical_calibration.rst
  smash/_constant.py
  smash/core/simulation/_doc.py
  smash/core/simulation/_standardize.py
  smash/core/simulation/optimize/_standardize.py
  smash/core/simulation/optimize/optimize.py
  smash/fcore/derived_type/mwd_optimize_options.f90
  smash/tests/core/simulation/test_optimize.py
Labels: backport

#439 DOC/ENH: Enhance README + minor corrections to getting started and contributor guide (#426)
  README.md
  doc/source/contributor_guide/development_process_details.rst
  doc/source/getting_started/index.rst
Labels: backport

#441 Prepare for patch release v1.1.1
  CITATIONS.rst
  doc/source/release/1.1.1-notes.rst
  doc/source/release/index.rst
  smash.bib
Labels: documentation

#445 MAINT: Windows wheel
  .github/workflows/wheel.yml
  doc/source/getting_started/index.rst
  f90wrap/generate_f2py-f90wrap.py
  smash/fcore/meson.build
Labels: bug
